import { Place, PlaceCategory } from '../model/types';
import { Accessibility } from '../../accessibility/model/types';

export const MOCK_PLACES: Place[] = [
  {
    id: '1',
    photo: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4',
    name: 'Starbucks Coffee',
    address: 'ул. Тверская, 15',
    localityId: 'moscow',
    accessibility: [Accessibility.MOTOR, Accessibility.VISUAL, Accessibility.HEARING],
    placeCategory: PlaceCategory.CAFE_RESTAURANT,
    rating: { count: '4.5', reviews: '328' },
    isApproved: true,
    entranceType: 'main',
    floor: '1',
    hasElevator: true,
    hasRamp: true,
    hasDisabledToilet: true,
    parking: {
      available: true,
      type: 'street',
      distance: '10 метров',
    },
  },
  {
    id: '2',
    photo: 'https://images.unsplash.com/photo-1540224871915-bc8ffb782bdf',
    name: 'Государственный Эрмитаж',
    address: 'Дворцовая площадь, 2',
    localityId: 'spb',
    accessibility: [
      Accessibility.MOTOR,
      Accessibility.VISUAL,
      Accessibility.HEARING,
      Accessibility.COGNITIVE,
    ],
    placeCategory: PlaceCategory.CULTURE,
    rating: { count: '4.9', reviews: '1245' },
    isApproved: true,
    entranceType: 'main',
    floor: '1-3',
    hasElevator: true,
    hasRamp: true,
    hasDisabledToilet: true,
    parking: {
      available: true,
      type: 'lot',
      distance: '50 метров',
    },
  },
  {
    id: '3',
    photo: 'https://images.unsplash.com/photo-1571607388263-1044f9ea01dd',
    name: 'Городская больница №1',
    address: 'ул. Ленина, 87',
    localityId: 'ekb',
    accessibility: [
      Accessibility.MOTOR,
      Accessibility.VISUAL,
      Accessibility.HEARING,
      Accessibility.SITUATIONAL,
    ],
    placeCategory: PlaceCategory.HEALTHCARE,
    rating: { count: '4.2', reviews: '89' },
    isApproved: true,
    entranceType: 'main',
    floor: '1-5',
    hasElevator: true,
    hasRamp: true,
    hasDisabledToilet: true,
    parking: {
      available: true,
      type: 'lot',
      distance: '20 метров',
    },
  },
  {
    id: '4',
    photo: 'https://images.unsplash.com/photo-1528109966605-5b6e6d5eaa4f',
    name: 'ТРЦ "Мега"',
    address: 'пр. Космонавтов, 14',
    localityId: 'novosibirsk',
    accessibility: [Accessibility.MOTOR, Accessibility.VISUAL, Accessibility.HEARING],
    placeCategory: PlaceCategory.SHOPPING,
    rating: { count: '4.3', reviews: '567' },
    isApproved: true,
    entranceType: 'main',
    floor: '1-4',
    hasElevator: true,
    hasRamp: true,
    hasDisabledToilet: true,
    parking: {
      available: true,
      type: 'garage',
      distance: '30 метров',
    },
  },
  {
    id: '5',
    photo: 'https://images.unsplash.com/photo-1570829460005-c840387bb1ca',
    name: 'Парк Горького',
    address: 'Крымский Вал, 9',
    localityId: 'moscow',
    accessibility: [Accessibility.MOTOR, Accessibility.VISUAL, Accessibility.COGNITIVE],
    placeCategory: PlaceCategory.PARK,
    rating: { count: '4.7', reviews: '892' },
    isApproved: true,
    entranceType: 'main',
    floor: '1',
    hasElevator: false,
    hasRamp: true,
    hasDisabledToilet: true,
    parking: {
      available: true,
      type: 'lot',
      distance: '15 метров',
    },
  },
  {
    id: '6',
    photo: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836',
    name: 'Ресторан "Пушкин"',
    address: 'ул. Байкальская, 25',
    localityId: 'kazan',
    accessibility: [Accessibility.MOTOR, Accessibility.VISUAL],
    placeCategory: PlaceCategory.CAFE_RESTAURANT,
    rating: { count: '4.8', reviews: '421' },
    isApproved: true,
    entranceType: 'main',
    floor: '1',
    hasElevator: false,
    hasRamp: true,
    hasDisabledToilet: true,
    parking: {
      available: true,
      type: 'street',
      distance: '5 метров',
    },
  },
  {
    id: '7',
    photo: 'https://images.unsplash.com/photo-1528837516156-0a7225a43641',
    name: 'Фитнес-центр "Атлетика"',
    address: 'ул. Спортивная, 3',
    localityId: 'nn',
    accessibility: [Accessibility.MOTOR, Accessibility.VISUAL],
    placeCategory: PlaceCategory.SPORTS,
    rating: { count: '4.4', reviews: '234' },
    isApproved: true,
    entranceType: 'main',
    floor: '1-2',
    hasElevator: true,
    hasRamp: true,
    hasDisabledToilet: true,
    parking: {
      available: true,
      type: 'lot',
      distance: '10 метров',
    },
  },
  {
    id: '8',
    photo: 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43',
    name: 'Сбербанк',
    address: 'пр. Ленина, 45',
    localityId: 'krasnodar',
    accessibility: [Accessibility.MOTOR, Accessibility.VISUAL, Accessibility.HEARING],
    placeCategory: PlaceCategory.BANK,
    rating: { count: '3.9', reviews: '156' },
    isApproved: true,
    entranceType: 'main',
    floor: '1',
    hasElevator: true,
    hasRamp: true,
    hasDisabledToilet: false,
    parking: {
      available: true,
      type: 'street',
      distance: '8 метров',
    },
  },
  {
    id: '9',
    photo: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64',
    name: 'Метро "Площадь Революции"',
    address: 'пл. Революции, 1',
    localityId: 'moscow',
    accessibility: [Accessibility.MOTOR, Accessibility.VISUAL, Accessibility.HEARING],
    placeCategory: PlaceCategory.TRANSPORT,
    rating: { count: '4.1', reviews: '678' },
    isApproved: true,
    entranceType: 'main',
    floor: '-2',
    hasElevator: true,
    hasRamp: true,
    hasDisabledToilet: true,
    parking: {
      available: false,
    },
  },
  {
    id: '10',
    photo: 'https://images.unsplash.com/photo-1566073771259-6a8506099945',
    name: 'Отель "Метрополь"',
    address: 'ул. Театральная, 2',
    localityId: 'moscow',
    accessibility: [Accessibility.MOTOR, Accessibility.VISUAL, Accessibility.HEARING],
    placeCategory: PlaceCategory.ACCOMMODATION,
    rating: { count: '4.6', reviews: '345' },
    isApproved: true,
    entranceType: 'main',
    floor: '1-8',
    hasElevator: true,
    hasRamp: true,
    hasDisabledToilet: true,
    parking: {
      available: true,
      type: 'garage',
      distance: '20 метров',
    },
  },
  {
    id: '11',
    photo: 'https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04',
    name: 'Кинотеатр "Формула Кино"',
    address: 'ул. Кирова, 12',
    localityId: 'vladivostok',
    accessibility: [Accessibility.MOTOR, Accessibility.VISUAL, Accessibility.HEARING],
    placeCategory: PlaceCategory.ENTERTAINMENT,
    rating: { count: '4.3', reviews: '278' },
    isApproved: true,
    entranceType: 'main',
    floor: '3-5',
    hasElevator: true,
    hasRamp: true,
    hasDisabledToilet: true,
    parking: {
      available: true,
      type: 'garage',
      distance: '15 метров',
    },
  },
  {
    id: '12',
    photo: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d',
    name: 'Аптека "36.6"',
    address: 'ул. Зеленая, 7',
    localityId: 'spb',
    accessibility: [Accessibility.MOTOR],
    placeCategory: PlaceCategory.PHARMACY,
    rating: { count: '4.0', reviews: '123' },
    isApproved: true,
    entranceType: 'main',
    floor: '1',
    hasElevator: false,
    hasRamp: false,
    hasDisabledToilet: false,
    parking: {
      available: false,
    },
  },
  {
    id: '13',
    photo: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72',
    name: 'Салон красоты "Элита"',
    address: 'ул. Мира, 33',
    localityId: 'ekb',
    accessibility: [Accessibility.MOTOR],
    placeCategory: PlaceCategory.HAIR_BEAUTY,
    rating: { count: '4.5', reviews: '189' },
    isApproved: true,
    entranceType: 'main',
    floor: '2',
    hasElevator: false,
    hasRamp: false,
    hasDisabledToilet: false,
  },
  {
    id: '14',
    photo: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb',
    name: 'Кафедральный собор',
    address: 'ул. Соборная, 1',
    localityId: 'novosibirsk',
    accessibility: [Accessibility.MOTOR, Accessibility.VISUAL],
    placeCategory: PlaceCategory.RELIGION,
    rating: { count: '4.7', reviews: '267' },
    isApproved: true,
    entranceType: 'main',
    floor: '1',
    hasElevator: false,
    hasRamp: true,
    hasDisabledToilet: true,
  },
  {
    id: '15',
    photo: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3',
    name: 'Детский сад "Солнышко"',
    address: 'ул. Детская, 5',
    localityId: 'kazan',
    accessibility: [Accessibility.MOTOR, Accessibility.VISUAL, Accessibility.COGNITIVE],
    placeCategory: PlaceCategory.EDUCATION,
    rating: { count: '4.4', reviews: '98' },
    isApproved: true,
    entranceType: 'main',
    floor: '1-2',
    hasElevator: false,
    hasRamp: true,
    hasDisabledToilet: true,
    parking: {
      available: true,
      type: 'lot',
      distance: '5 метров',
    },
  },
  {
    id: '16',
    photo: 'https://images.unsplash.com/photo-1560472354-b33ff0c44a43',
    name: 'Кофейня "Кофе Хауз"',
    address: 'пр. Победы, 21',
    localityId: 'nn',
    accessibility: [Accessibility.MOTOR],
    placeCategory: PlaceCategory.CAFE_RESTAURANT,
    rating: { count: '4.2', reviews: '312' },
    isApproved: true,
    entranceType: 'main',
    floor: '1',
    hasElevator: false,
    hasRamp: true,
    hasDisabledToilet: false,
  },
  {
    id: '17',
    photo: 'https://images.unsplash.com/photo-1573164713988-8665fc963095',
    name: 'Аквапарк "Океан"',
    address: 'ул. Водная, 8',
    localityId: 'krasnodar',
    accessibility: [Accessibility.MOTOR, Accessibility.VISUAL],
    placeCategory: PlaceCategory.ENTERTAINMENT,
    rating: { count: '4.8', reviews: '456' },
    isApproved: true,
    entranceType: 'main',
    floor: '1-3',
    hasElevator: true,
    hasRamp: true,
    hasDisabledToilet: true,
    parking: {
      available: true,
      type: 'lot',
      distance: '25 метров',
    },
  },
  {
    id: '18',
    photo: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3',
    name: 'Магазин "Магнит"',
    address: 'ул. Центральная, 42',
    localityId: 'vladivostok',
    accessibility: [Accessibility.MOTOR],
    placeCategory: PlaceCategory.SHOPPING,
    rating: { count: '3.8', reviews: '134' },
    isApproved: true,
    entranceType: 'main',
    floor: '1',
    hasElevator: false,
    hasRamp: false,
    hasDisabledToilet: false,
  },
  {
    id: '19',
    photo: 'https://images.unsplash.com/photo-1579931794097-0ad001e51edb',
    name: 'Библиотека им. Ленина',
    address: 'ул. Книжная, 15',
    localityId: 'moscow',
    accessibility: [Accessibility.MOTOR, Accessibility.VISUAL, Accessibility.HEARING],
    placeCategory: PlaceCategory.EDUCATION,
    rating: { count: '4.5', reviews: '189' },
    isApproved: true,
    entranceType: 'main',
    floor: '1-4',
    hasElevator: true,
    hasRamp: true,
    hasDisabledToilet: true,
  },
  {
    id: '20',
    photo: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12',
    name: 'Станция технического обслуживания',
    address: 'ул. Автомобильная, 30',
    localityId: 'spb',
    accessibility: [Accessibility.MOTOR],
    placeCategory: PlaceCategory.SERVICES,
    rating: { count: '4.1', reviews: '87' },
    isApproved: true,
    entranceType: 'main',
    floor: '1',
    hasElevator: false,
    hasRamp: false,
    hasDisabledToilet: false,
    parking: {
      available: true,
      type: 'lot',
      distance: '2 метра',
    },
  },
  {
    id: '21',
    photo: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d',
    name: 'Офис Google',
    address: 'ул. Балчуг, 7',
    localityId: 'moscow',
    accessibility: [Accessibility.MOTOR, Accessibility.VISUAL, Accessibility.HEARING],
    placeCategory: PlaceCategory.OFFICE,
    rating: { count: '4.9', reviews: '56' },
    isApproved: true,
    entranceType: 'main',
    floor: '10-15',
    hasElevator: true,
    hasRamp: true,
    hasDisabledToilet: true,
    parking: {
      available: true,
      type: 'garage',
      distance: '30 метров',
    },
  },
  {
    id: '22',
    photo: 'https://images.unsplash.com/photo-1573247375456-3ca49ae21016',
    name: 'МФЦ "Мои документы"',
    address: 'ул. Павла Корчагина, 3',
    localityId: 'ekb',
    accessibility: [Accessibility.MOTOR, Accessibility.VISUAL, Accessibility.HEARING],
    placeCategory: PlaceCategory.GOVERNMENT,
    rating: { count: '3.7', reviews: '234' },
    isApproved: true,
    entranceType: 'main',
    floor: '1',
    hasElevator: true,
    hasRamp: true,
    hasDisabledToilet: true,
  },
  {
    id: '23',
    photo: 'https://images.unsplash.com/photo-1515168833906-d2a3b82b5d63',
    name: 'Суши-бар "Токио"',
    address: 'ул. Японская, 11',
    localityId: 'novosibirsk',
    accessibility: [Accessibility.MOTOR],
    placeCategory: PlaceCategory.CAFE_RESTAURANT,
    rating: { count: '4.4', reviews: '178' },
    isApproved: true,
    entranceType: 'main',
    floor: '1',
    hasElevator: false,
    hasRamp: true,
    hasDisabledToilet: false,
  },
  {
    id: '24',
    photo: 'https://images.unsplash.com/photo-1519677100203-5f3a5d4f09f7',
    name: 'Спортивный комплекс "Олимпийский"',
    address: 'пр. Олимпийский, 16',
    localityId: 'kazan',
    accessibility: [Accessibility.MOTOR, Accessibility.VISUAL, Accessibility.HEARING],
    placeCategory: PlaceCategory.SPORTS,
    rating: { count: '4.6', reviews: '321' },
    isApproved: true,
    entranceType: 'main',
    floor: '1-3',
    hasElevator: true,
    hasRamp: true,
    hasDisabledToilet: true,
    parking: {
      available: true,
      type: 'lot',
      distance: '20 метров',
    },
  },
  {
    id: '25',
    photo: 'https://images.unsplash.com/photo-1553531768-9dd6d1c1f4b0',
    name: 'Вокзал "Казань-Пассажирская"',
    address: 'пл. Вокзальная, 1',
    localityId: 'kazan',
    accessibility: [Accessibility.MOTOR, Accessibility.VISUAL, Accessibility.HEARING],
    placeCategory: PlaceCategory.TRANSPORT,
    rating: { count: '4.0', reviews: '456' },
    isApproved: true,
    entranceType: 'main',
    floor: '1-2',
    hasElevator: true,
    hasRamp: true,
    hasDisabledToilet: true,
    parking: {
      available: true,
      type: 'lot',
      distance: '50 метров',
    },
  },
  {
    id: '26',
    photo: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91',
    name: 'Гостиница "Волга"',
    address: 'наб. Волги, 25',
    localityId: 'nn',
    accessibility: [Accessibility.MOTOR, Accessibility.VISUAL],
    placeCategory: PlaceCategory.ACCOMMODATION,
    rating: { count: '3.9', reviews: '145' },
    isApproved: true,
    entranceType: 'main',
    floor: '1-7',
    hasElevator: true,
    hasRamp: true,
    hasDisabledToilet: true,
  },
  {
    id: '27',
    photo: 'https://images.unsplash.com/photo-1582719508461-905c673771fd',
    name: 'Круглосуточная аптека',
    address: 'ул. Ночная, 3',
    localityId: 'krasnodar',
    accessibility: [Accessibility.MOTOR],
    placeCategory: PlaceCategory.PHARMACY,
    rating: { count: '4.1', reviews: '92' },
    isApproved: true,
    entranceType: 'main',
    floor: '1',
    hasElevator: false,
    hasRamp: true,
    hasDisabledToilet: false,
  },
  {
    id: '28',
    photo: 'https://images.unsplash.com/photo-1511578314322-379afb476865',
    name: 'Боулинг-клуб "Страйк"',
    address: 'ул. Развлекательная, 9',
    localityId: 'vladivostok',
    accessibility: [Accessibility.MOTOR, Accessibility.HEARING],
    placeCategory: PlaceCategory.ENTERTAINMENT,
    rating: { count: '4.3', reviews: '167' },
    isApproved: true,
    entranceType: 'main',
    floor: '2',
    hasElevator: true,
    hasRamp: true,
    hasDisabledToilet: true,
  },
  {
    id: '29',
    photo: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2',
    name: 'Пиццерия "Додо Пицца"',
    address: 'ул. Пиццерийная, 4',
    localityId: 'moscow',
    accessibility: [Accessibility.MOTOR],
    placeCategory: PlaceCategory.CAFE_RESTAURANT,
    rating: { count: '4.6', reviews: '589' },
    isApproved: true,
    entranceType: 'main',
    floor: '1',
    hasElevator: false,
    hasRamp: true,
    hasDisabledToilet: false,
    parking: {
      available: true,
      type: 'street',
      distance: '5 метров',
    },
  },
  {
    id: '30',
    photo: 'https://images.unsplash.com/photo-1563903530908-afdd155d057a',
    name: 'Стоматологическая клиника "Дентал"',
    address: 'ул. Стоматологическая, 12',
    localityId: 'spb',
    accessibility: [Accessibility.MOTOR, Accessibility.VISUAL, Accessibility.HEARING],
    placeCategory: PlaceCategory.HEALTHCARE,
    rating: { count: '4.7', reviews: '276' },
    isApproved: true,
    entranceType: 'main',
    floor: '2',
    hasElevator: true,
    hasRamp: true,
    hasDisabledToilet: true,
  },
];

export const ENTRANCE_TYPE_CONFIG = {
  main: { label: 'Главный вход', color: 'green' },
  secondary: { label: 'Доп. вход', color: 'blue' },
  service: { label: 'Служебный вход', color: 'orange' },
};

export const CATEGORIES: Record<PlaceCategory, any> = {
  [PlaceCategory.CAFE_RESTAURANT]: {
    id: PlaceCategory.CAFE_RESTAURANT,
    name: 'Кафе и рестораны',
    description: 'Заведения общественного питания',
    icon: '🍽️',
    color: '#ff6b6b',
    emoji: '🍕',
    subcategories: ['Кафе', 'Ресторан', 'Столовая', 'Фастфуд', 'Кофейня', 'Бар'],
    tags: ['еда', 'питание', 'рестораны', 'кафе'],
  },
  [PlaceCategory.SHOPPING]: {
    id: PlaceCategory.SHOPPING,
    name: 'Магазины и торговля',
    description: 'Торговые центры, магазины, супермаркеты',
    icon: '🛒',
    color: '#4ecdc4',
    emoji: '🛍️',
    subcategories: ['Супермаркет', 'ТЦ', 'Бутик', 'Продуктовый', 'Одежда', 'Электроника'],
    tags: ['покупки', 'шоппинг', 'магазин'],
  },
  [PlaceCategory.HEALTHCARE]: {
    id: PlaceCategory.HEALTHCARE,
    name: 'Здравоохранение',
    description: 'Медицинские учреждения и аптеки',
    icon: '🏥',
    color: '#45b7d1',
    emoji: '👨‍⚕️',
    subcategories: ['Поликлиника', 'Больница', 'Стоматология', 'Медцентр', 'Лаборатория'],
    tags: ['медицина', 'здоровье', 'врач'],
  },
  [PlaceCategory.SPORTS]: {
    id: PlaceCategory.SPORTS,
    name: 'Спорт и фитнес',
    description: 'Спортивные объекты и фитнес-центры',
    icon: '⚽',
    color: '#96ceb4',
    emoji: '🏋️',
    subcategories: ['Спортзал', 'Бассейн', 'Стадион', 'Йога', 'Тренажеры'],
    tags: ['спорт', 'фитнес', 'тренировка'],
  },
  [PlaceCategory.CULTURE]: {
    id: PlaceCategory.CULTURE,
    name: 'Культура и искусство',
    description: 'Музеи, театры, галереи',
    icon: '🎭',
    color: '#ffcc5c',
    emoji: '🎨',
    subcategories: ['Музей', 'Театр', 'Галерея', 'Кинотеатр', 'Концертный зал'],
    tags: ['культура', 'искусство', 'развлечения'],
  },
  [PlaceCategory.EDUCATION]: {
    id: PlaceCategory.EDUCATION,
    name: 'Образование',
    description: 'Учебные заведения и библиотеки',
    icon: '📚',
    color: '#5c6bc0',
    emoji: '🎓',
    subcategories: ['Школа', 'ВУЗ', 'Колледж', 'Библиотека', 'Курсы'],
    tags: ['образование', 'учеба', 'обучение'],
  },
  [PlaceCategory.TRANSPORT]: {
    id: PlaceCategory.TRANSPORT,
    name: 'Транспорт',
    description: 'Остановки, вокзалы, аэропорты',
    icon: '🚌',
    color: '#ffa726',
    emoji: '🚉',
    subcategories: ['Вокзал', 'Аэропорт', 'Остановка', 'Метро', 'Парковка'],
    tags: ['транспорт', 'поездка', 'перевозки'],
  },
  [PlaceCategory.OFFICE]: {
    id: PlaceCategory.OFFICE,
    name: 'Офисы и бизнес',
    description: 'Офисные здания и деловые центры',
    icon: '🏢',
    color: '#78909c',
    emoji: '💼',
    subcategories: ['Офис', 'Коворкинг', 'Деловой центр', 'Банк'],
    tags: ['работа', 'офис', 'бизнес'],
  },
  [PlaceCategory.ACCOMMODATION]: {
    id: PlaceCategory.ACCOMMODATION,
    name: 'Жилье',
    description: 'Отели, гостиницы, хостелы',
    icon: '🏨',
    color: '#ab47bc',
    emoji: '🛏️',
    subcategories: ['Отель', 'Гостиница', 'Хостел', 'Апартаменты'],
    tags: ['ночлег', 'отдых', 'гостиница'],
  },
  [PlaceCategory.SERVICES]: {
    id: PlaceCategory.SERVICES,
    name: 'Услуги',
    description: 'Бытовые и профессиональные услуги',
    icon: '🔧',
    color: '#26a69a',
    emoji: '🧰',
    subcategories: ['Парикмахерская', 'Химчистка', 'Ремонт', 'Почта', 'Копицентр'],
    tags: ['услуги', 'сервис', 'бытовые'],
  },
  [PlaceCategory.GOVERNMENT]: {
    id: PlaceCategory.GOVERNMENT,
    name: 'Государственные учреждения',
    description: 'Органы власти и госуслуги',
    icon: '🏛️',
    color: '#7e57c2',
    emoji: '📋',
    subcategories: ['МФЦ', 'Почта', 'ЗАГС', 'Пенсионный фонд', 'Налоговая'],
    tags: ['государство', 'услуги', 'официально'],
  },
  [PlaceCategory.ENTERTAINMENT]: {
    id: PlaceCategory.ENTERTAINMENT,
    name: 'Развлечения',
    description: 'Клубы, аттракционы, игровые центры',
    icon: '🎪',
    color: '#ef5350',
    emoji: '🎮',
    subcategories: ['Клуб', 'Боулинг', 'Караоке', 'Игровая зона', 'Аттракционы'],
    tags: ['развлечения', 'отдых', 'досуг'],
  },
  [PlaceCategory.PARK]: {
    id: PlaceCategory.PARK,
    name: 'Парки и отдых',
    description: 'Парки, скверы, зоны отдыха',
    icon: '🌳',
    color: '#66bb6a',
    emoji: '🌲',
    subcategories: ['Парк', 'Сквер', 'Набережная', 'Площадь', 'Аллея'],
    tags: ['отдых', 'природа', 'прогулка'],
  },
  [PlaceCategory.BANK]: {
    id: PlaceCategory.BANK,
    name: 'Банки',
    description: 'Банковские учреждения',
    icon: '🏦',
    color: '#5c6bc0',
    emoji: '💰',
    subcategories: ['Банк', 'Банкомат', 'Отделение'],
    tags: ['финансы', 'банк', 'деньги'],
  },
  [PlaceCategory.PHARMACY]: {
    id: PlaceCategory.PHARMACY,
    name: 'Аптеки',
    description: 'Аптеки и лекарства',
    icon: '💊',
    color: '#ff7043',
    emoji: '🧪',
    subcategories: ['Аптека', 'Дежурная аптека', 'Ветеринарная аптека'],
    tags: ['лекарства', 'здоровье', 'медицина'],
  },
  [PlaceCategory.HAIR_BEAUTY]: {
    id: PlaceCategory.HAIR_BEAUTY,
    name: 'Красота и уход',
    description: 'Салоны красоты и SPA',
    icon: '💇',
    color: '#ec407a',
    emoji: '💅',
    subcategories: ['Парикмахерская', 'Салон красоты', 'SPA', 'Маникюр', 'Массаж'],
    tags: ['красота', 'уход', 'салон'],
  },
  [PlaceCategory.RELIGION]: {
    id: PlaceCategory.RELIGION,
    name: 'Религиозные объекты',
    description: 'Храмы, церкви, мечети',
    icon: '⛪',
    color: '#8d6e63',
    emoji: '🕌',
    subcategories: ['Церковь', 'Храм', 'Мечеть', 'Синагога', 'Монастырь'],
    tags: ['религия', 'духовность', 'храм'],
  },
  [PlaceCategory.OTHER]: {
    id: PlaceCategory.OTHER,
    name: 'Другое',
    description: 'Прочие места',
    icon: '📍',
    color: '#bdbdbd',
    emoji: '❓',
    subcategories: [],
    tags: ['другое'],
  },
};
